# Stage 1: Build frontend
FROM node:20-alpine AS frontend-builder

COPY ./frontend /app

WORKDIR /app

RUN npm install
RUN npm run build




# Stage 2: Backend
FROM node:20-alpine

COPY ./backend /app
WORKDIR /app
RUN npm install

# Copy built frontend from the previous stage
COPY --from=frontend-builder /app/dist /app/public

CMD ["node", "Server.js"]